<?php

return [
    'default_route' => 'siwa_lasusua',

    'routes' => [
        'siwa_lasusua' => [
            'label' => 'Siwa - Lasusua',

            'items' => [
                [
                    'code' => 'penumpang_dewasa',
                    'group' => 'Penumpang',
                    'label' => 'Dewasa',
                    'description' => 'Penumpang Dewasa',
                    'unit' => 'orang',
                    'price' => 58300,
                ],
                [
                    'code' => 'penumpang_bayi',
                    'group' => 'Penumpang',
                    'label' => 'Bayi',
                    'description' => 'Penumpang Bayi',
                    'unit' => 'orang',
                    'price' => 6000,
                ],
                [
                    'code' => 'golongan_1',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan I',
                    'description' => 'Kendaraan Golongan I',
                    'unit' => 'unit',
                    'price' => 66000,
                ],
                [
                    'code' => 'golongan_2',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan II',
                    'description' => 'Kendaraan Golongan II',
                    'unit' => 'unit',
                    'price' => 115000,
                ],
                [
                    'code' => 'golongan_3',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan III',
                    'description' => 'Kendaraan Golongan III',
                    'unit' => 'unit',
                    'price' => 233200,
                ],
                [
                    'code' => 'golongan_4_penumpang',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan IV - Kendaraan Penumpang',
                    'description' => 'Golongan IV A - Kendaraan Penumpang',
                    'unit' => 'unit',
                    'price' => 888800,
                ],
                [
                    'code' => 'golongan_4_barang',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan IV - Kendaraan Barang',
                    'description' => 'Golongan IV B - Kendaraan Barang',
                    'unit' => 'unit',
                    'price' => 922900,
                ],
                [
                    'code' => 'golongan_5_penumpang',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan V - Kendaraan Penumpang',
                    'description' => 'Golongan V A - Kendaraan Penumpang',
                    'unit' => 'unit',
                    'price' => 1598400,
                ],
                [
                    'code' => 'golongan_5_barang',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan V - Kendaraan Barang',
                    'description' => 'Golongan V B - Kendaraan Barang',
                    'unit' => 'unit',
                    'price' => 1652500,
                ],
                [
                    'code' => 'golongan_6_penumpang',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan VI - Kendaraan Penumpang',
                    'description' => 'Golongan VI A - Kendaraan Penumpang',
                    'unit' => 'unit',
                    'price' => 2153000,
                ],
                [
                    'code' => 'golongan_6_barang',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan VI - Kendaraan Barang',
                    'description' => 'Golongan VI B - Kendaraan Barang',
                    'unit' => 'unit',
                    'price' => 2158800,
                ],
                [
                    'code' => 'golongan_7',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan VII',
                    'description' => 'Kendaraan Golongan VII',
                    'unit' => 'unit',
                    'price' => 3252300,
                ],
                [
                    'code' => 'golongan_8',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan VIII',
                    'description' => 'Kendaraan Golongan VIII',
                    'unit' => 'unit',
                    'price' => 3556800,
                ],
                [
                    'code' => 'golongan_9',
                    'group' => 'Kendaraan',
                    'label' => 'Golongan IX',
                    'description' => 'Kendaraan Golongan IX',
                    'unit' => 'unit',
                    'price' => 4364800,
                ],
            ],
        ],
    ],
];
